[package]
name = "aoc_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
gen_days = { workspace = true }
aoc_table = { workspace = true }
utils = { workspace = true }
arrayvec = "0.7.6"

[lib]
path = "lib.rs"


