[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_table = { git = "https://github.com/samhamnam/aoc_table" }
chrono = "0.4.22"
rayon = "1.6.0"
rand = "0.8.5"
zipperoni = { git = "https://github.com/samhamnam/zipperoni" }
num = "0.4.0"