[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
draw = []

[dependencies]
aoc_table = { git = "https://github.com/samhamnam/aoc_table" }
chrono = "0.4.23"
rayon = "1.6.1"
rand = "0.8.5"
zipperoni = { git = "https://github.com/samhamnam/zipperoni" }
serde = { version="1.0.149", features=["derive"] }
serde_json = "1.0.91"
pathfinding = "4.0.1"
memoize = "0.3.3"