on: [push]
jobs:
  benchmarks:
    runs-on: docker
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install Rust
      uses: https://github.com/continuwuity/continuwuity/.forgejo/actions/rust-toolchain@v0.5.0-rc.7
    - name: Fetch Inputs
      run: |
        mkdir -p ~/.ssh/ 
        echo "HOST *" > ~/.ssh/config
        echo "StrictHostKeyChecking no" >> ~/.ssh/config
        eval `ssh-agent -s`
        ssh-add - <<< '${{ secrets.SSH_KEY }}'
        git clone ssh://git@100.74.251.100:2222/loafey/advent_of_code_inputs.git inputs
    - name: Benchmarks
      run: |
        bash run-benchmark.sh
