[package]
name = "aoc_2018"
version = "0.1.0"
edition = "2021"

[dependencies]
gen_days = { workspace = true }
aoc_table = { workspace = true }
utils = { workspace = true }
rayon = { workspace = true }
chrono = { workspace = true }

[lib]
path = "lib.rs"


